### ISSUE TITLE
jsDelivrCDN资源错误

### ISSUE THREAD

**Issue by mole9630** [qr-merger/merger#29]
jsDelivr的资源似乎挂掉了，导致全站样式和内容全部错乱了。

**Comment by hifocus** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18348

似乎中国大陆的 jsDelivr 暂时挂了。
可以切换到备用知乎源，或者等待官方修复。

**Comment by hifocus** [comment]
jsDelivr has lost its ICP license.

In the future we will consider switching to local open source CDN providers because of speed considerations.

**Comment by hifocus** [comment]
Some initial thoughts:

Merger's future self-written static files, namely style.css and function.js, will be served via Zhihu's NPM mirror (or Baidu's).

Other third-party static libraries, such as jQuery, will be served via a local(Chinese) CDN, that meets a high standard at its operation.
