### ISSUE TITLE
Please Update to Version 0.27.1

### ISSUE THREAD

**Issue by hifocus** [qr-merger/merger#32]
[Update 27.1](https://github.com/qr-merger/merger/releases/tag/0.27.1) transitioned the use of jsDelivr static files to local files, amid the jsDelivr block in China https://github.com/jsdelivr/jsdelivr/issues/18392. It also removed the previous Gravatar mirror because of its poor service status.

Please update to [version 0.27.1](https://github.com/qr-merger/merger/releases/tag/0.27.1) to keep jsDelivr working. Thanks.

**Comment by fenghaoran-haoran** [comment]
感谢开源，有个问题，在微信中打开识别不到收款码。

**Comment by hifocus** [comment]
> 感谢开源，有个问题，在微信中打开识别不到收款码。

感谢反馈。在 https://demo2.qrcdn.com 上测试，如果使用自己的微信尝试长按识别二维码，则二维码识别按钮会消失。这个是微信自己的限制。不使用自己的账号扫描自己的就好。比如下图，使用小号扫描大号，则个可以出现识别按钮，按下后也可以成功弹出支付界面。

![image](https://user-images.githubusercontent.com/30528433/179069959-0a86f1ae-8590-45cd-8c93-f941a9bdbec3.png)

欢迎[自行测试](https://chart.googleapis.com/chart?chs=500x500&cht=qr&chl=https%3A%2F%2Fdemo2.qrcdn.com%2F&chld=L|1&choe=UTF-8)；如果问题依然存在，请指出出现问题时的微信版本，操作系统，User Agent 等等以帮助解决问题。

**Comment by longsays** [comment]
使用<a href="https://chart.googleapis.com/chart?chs=500x500&amp;cht=qr&amp;chl=https%3A%2F%2Fdemo2.qrcdn.com%2F&amp;chld=L%7C1&amp;choe=UTF-8" rel="nofollow">测试样例</a> ，问题依然存在 ， Android 11
![20220731110532](https://user-images.githubusercontent.com/1893659/182008146-9bbd42d1-b268-4af5-910b-64986858c568.png)
![20220731110559](https://user-images.githubusercontent.com/1893659/182008152-28e8025f-315b-4af9-bcce-4c14594d0bdf.png)

**Comment by hifocus** [comment]
使用安卓微信测试，无论是版本 8.0.21 还是 25，均能够识别其他人的二维码。

![image](https://user-images.githubusercontent.com/30528433/182029916-d03ae28a-6030-4656-8ff6-cf8bedfa0356.png)

User agent: `Mozilla/5.0 (Linux; Android 10; MI 8 Build/QKQ1.190828.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/3185 MMWEBSDK/20220706 Mobile Safari/537.36 MMWEBID/9159 MicroMessenger/8.0.25.2200(0x28001937) WeChat/arm64 Weixin NetType/WIFI Language/zh_CN ABI/arm64`

暂时无法确认问题。
